### ISSUE TITLE
ArgoCD Bootstrap Application fails to Synchronize

### ISSUE THREAD

**Issue by deleeuwblue** [cloud-native-toolkit/image-cli-tools#101]
I ran a test to deploy a BOM including OpenShift and ArgoCD.  The test worked fine using Multipass, but fails when using Docker and the cli-tools container.

The OpenShift cluster is installed, but ArgoCD fails to synchronize the Bootstrap Application.  It reports the following error:

```
Ignoring non-table value ([]) Error: template: default/charts/services/templates/project.yaml:1:26: executing "default/charts/services/templates/project.yaml" at <include "argocd.destinations" .Values.global.destinations>: error calling include: template: default/charts/applications/templates/_helpers.tpl:12:7: executing "argocd.destinations" at <.targetNamespace>: can't evaluate field targetNamespace in type interface {} Use --debug flag to render out invalid YAML
```

@binnes and I did some investigation.  We found that when using the cli-tools container, the `main/argocd/0-bootstrap/cluster/default/values.yaml ` file in GitOps is generated differently vs when using Multipass.

Using cli-tools, it is generated like this:
```
global:
  repoUrl: https://github.com/deleeuwblue/watsondemogitDocker.git
  targetRevision: main
  targetNamespace: openshift-gitops
  destinations:
    targetNamespace: '*'
  pathSuffix: cluster/default
  prefix: ''
```

Using Multipass, it is generated like this:
```
global:
  repoUrl: https://github.com/deleeuwblue/watsondemogit.git
  targetRevision: main
  targetNamespace: openshift-gitops
  destinations:
    - targetNamespace: '*'
  pathSuffix: cluster/default
  prefix: ''
```

Note there is a '-' missing ahead of 'targetNamespace' with cli-tools.  When this is corrected in the GitOps file, ArgoCD is able to successfully synchronize the Bootstrap Application.

One possible cause could be a mismatch with the `yq` versions.  With Multipass, the cli-tools.yaml installs v4.25.2.  The cli-tools container includes v4.27.2.
